# from selenium import  webdriver
# from time import sleep
# dr = webdriver.Chrome()
# # dr.get("https://www.baidu.com")
# # sleep(2)
# # print(dr.current_url)
# # dr.set_window_size(400,400)
# # sleep(2)
# # dr.set_window_position(400,400)
# # sleep(2)
# # dr.maximize_window()
# # sleep(2)
# # dr.minimize_window()
# dr.get("https://www.baidu.com")
# sleep(2)
# # dr.get("https://www.jd.com")
# # sleep(2)
# # dr.back()
# # sleep(2)
# # dr.forward()
# dr.maximize_window()
# sleep(5)
# # dr.find_element_by_name("wd").send_keys("python")
# # sleep(2)
# # dr.find_element_by_id("su").click()
# # # sleep(2)
# # # dr.back()
# # dr.find_element_by_link_text("hao123").click()
# dr.find_element_by_xpath("//*[@id="u1']/a[1]').click()
